name: AssistDebugStick
version: ${project.version}
main: com.github.kedaryu.assistdebugstick.AssistDebugStick
api-version: 1.16
commands:
  ads:
    usage: /ads <help>
    description: AssistDebugStick Command
    permissions: AssistDebugStick.ads
  assistdebugstick:
    usage: /assistdebugstick <help>
    description: AssistDebugStick Command
    permissions: AssistDebugStick.assistdebugstick
permissions:
  AssistDebugStick.ads:
    default: op
  AssistDebugStick.assistdebugstick:
    default: op
